version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  install:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.14'
      - run: node --version

workflows:
  test_my_app:
    jobs:
      - install
      - node/run:
          npm-run: build
          app-dir: ~/project/src
      - node/test:
          test-results-for: jest
          app-dir: ~/project/src