version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  init:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.14'
      - run: node --version
      - environment:
          ACCESS_ID: $ACCESS_ID
          ACCESS_KEY: $ACCESS_KEY
          ENDPOINT: $ENDPOINT
          REGION: $REGION

workflows:
  test_my_app:
    jobs:
      - init
      - node/test:
          test-results-for: jest
          app-dir: ~/project/src