# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
jobs:
  build:
    working_directory: .
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: pwd
          command: pwd
      - run:
          name: Directories
          command: ls
      - run:
          name: Run build
          command: npm run build
